## Bridge configuration
connection radiohound_bridge
address radiohound.ee.nd.edu:1883 
cleansession true
start_type automatic
restart_timeout 10 60
#bridge_reload_type immediate
notifications false
topic radiohound/clients/data/# out 0