## Tunnel Bridge configuration
connection tunnel_bridge
address 127.0.0.1:8083
cleansession true
start_type automatic
restart_timeout 60
#bridge_reload_type immediate
notifications false
topic radiohound/clients/data/# out 0